const express=require("express"),fs=require("fs"),path=require("path"),app=express(),PORT=process.env.PORT||3000;
app.use(express.json({limit:"10mb"}));
app.use(express.static(__dirname));
if(!fs.existsSync(path.join(__dirname,"data")))fs.mkdirSync(path.join(__dirname,"data"));
const F=path.join(__dirname,"data","kc_data.json");
const DEF={users:[{id:"boss",name:"Boss KC",role:"boss",pin:"0000",dept:null,canManage:true,canViewAll:true,canScore:true,avatar:null}],employees:[],vehicles:[],logoUrl:null,bonusConfig:null,feedbacks:[],attendance:{},gameLogs:[]};
if(!fs.existsSync(F))fs.writeFileSync(F,JSON.stringify(DEF),"utf8");
const R=()=>JSON.parse(fs.readFileSync(F,"utf8"));
const W=(d)=>fs.writeFileSync(F,JSON.stringify(d,null,2),"utf8");
app.get("/api/data",(q,r)=>{try{r.json(R())}catch(e){r.json(DEF)}});
app.post("/api/users",(q,r)=>{try{const d=R();d.users=q.body;W(d);r.json({ok:true})}catch(e){r.status(500).json({error:e.message})}});
app.post("/api/employees",(q,r)=>{try{const d=R();d.employees=q.body;W(d);r.json({ok:true})}catch(e){r.status(500).json({error:e.message})}});
app.post("/api/vehicles",(q,r)=>{try{const d=R();d.vehicles=q.body;W(d);r.json({ok:true})}catch(e){r.status(500).json({error:e.message})}});
app.post("/api/logo",(q,r)=>{try{const d=R();d.logoUrl=q.body.logoUrl;W(d);r.json({ok:true})}catch(e){r.status(500).json({error:e.message})}});
app.post("/api/bonusConfig",(q,r)=>{try{const d=R();d.bonusConfig=q.body;W(d);r.json({ok:true})}catch(e){r.status(500).json({error:e.message})}});
app.post("/api/feedbacks",(q,r)=>{try{const d=R();d.feedbacks=q.body;W(d);r.json({ok:true})}catch(e){r.status(500).json({error:e.message})}});
app.post("/api/attendance",(q,r)=>{try{const d=R();d.attendance=q.body;W(d);r.json({ok:true})}catch(e){r.status(500).json({error:e.message})}});
app.post("/api/gameLogs",(q,r)=>{try{const d=R();d.gameLogs=q.body;W(d);r.json({ok:true})}catch(e){r.status(500).json({error:e.message})}});
app.get("*",(q,r)=>r.sendFile(path.join(__dirname,"index.html")));
app.listen(PORT,()=>console.log("KC KPI on port "+PORT));
